name: Verify if podman run works

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  schedule:
    - cron: "5 4 * * *"

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: uname -r
      run: |
        uname -r
    
    
    - name: crun --version
      run: |
        crun --version


    - name: podman --version
      run: |
        podman --version

    - name: podman info
      run: |
        podman info


    - name: podman run
      run: podman run fedora uname -a
